### ISSUE TITLE
Live demo not work (missing mp3)

### ISSUE THREAD

**Issue by boozook** [Masadow/FlxTilemap#1]
at http://tiagoling.com/uploads/iso_tilemap/html5/index.html

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (beep.mp3, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (flixel.mp3, line 0)
```

**Comment by Masadow** [comment]
Hey fzzr !

Thanks for your report. I'll see with @Tiago-Ling when he'll be able to fix that. This issue has concerned with its server configuration.

**Comment by Tiago-Ling** [comment]
Hi @fzzr-, i just tested here with a clean cache in Chrome and in different machines and i wasn't able to reproduce your problem.

The strange thing is that in html5 target flixel uses `ogg` files instead of `mp3`. 

I'll try reuploading the files, could you please test again and report if the problem was solved? 

Thanks! :)

**Comment by boozook** [comment]
Currently not works :(
http://tiagoling.com/uploads/iso_tilemap/html5/assets/sounds/beep.mp3 returning `404 Not Found` by nginx/1.4.4.

Caches cleared and totally disabled. OS X 10.10.3 (14D105g), Safari 8.0.5 (10600.5.9).

**Comment by Tiago-Ling** [comment]
Alright, i still don't understand why this problem is happening, but i uploaded the missing mp3 files to the html5 `assets` directory. 

This time it _should_ work.

Also, @Masadow, are you experiencing the same problem?

**Comment by boozook** [comment]
![out min](https://cloud.githubusercontent.com/assets/888526/6770150/0990ca16-d0c9-11e4-8239-eda68d709ca4.gif)

**Comment by Tiago-Ling** [comment]
I can confirm the problem is happening here also if i'm using Safari. The preloader stops at the end (about 80%) and the demo freezes before showing anything.

The console reports this problem:

```
[Error] TypeError: undefined is not an object (evaluating 'safari.application.addEventListener')
    global code (main.js, line 1)
```

I think this might be caused by something inside the `index.html` file - there might be something missing and/or in the wrong place. 

I'm looking into it as we speak, but for now could you test the demo with Chrome to check if the problem also happens for you there? 

I tested in `OSX 10.10.1`, using `Safari 8.0.2 (10600.2.5)`.

The demo runs fine using `Chrome 41.0.2272.89 (64-bit)` here.

**Comment by Tiago-Ling** [comment]
This might be a problem in HaxeFlixel - someone else also had it:

https://github.com/HaxeFlixel/flixel/issues/1462

**Comment by sruloart** [comment]
I can't test it (no Apple products available), but this looks like a well known problem with OpenFL's SoundJS trying to load an audio file format that isn't 100% compatible with whatever SoundJS is willing to load (on the specific target's browser). 

There is a very long thread over OpenFL forum about this, and there are a few things that work, like setting embed to false, using *.m4a file format, using *.wav or trying to make a better *.ogg (not guaranteed to work and quite tricky to use with all targets). 

In any case the first order of business when building a html5 Flixel project is to delete all reference to the *.mp3 and *.ogg that Flixel uses for the splash screen, or you're going to have problems with several html5 targets. 

Anyhow, audio with html5 is still a major problem for everyone, not just OpenFL, and Flixel doesn't do anything special when loading sound; it's all just plain OpenFL methods.

**Comment by Tiago-Ling** [comment]
I didn't know that, i think mostly because i rarely use HTML5 + Safari. The demo works in Windows using Chrome, Firefox or Internet Explorer and also works in OSX using Chrome (haven't tested Firefox, but i think it'll work too).

Good to know that @sruloart, thanks for the heads up!
